import { useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import myImage from "../public/mugshot.jpg";
import {
	StyledMain,
	StyledSection,
} from "../components/styledComponents/StyledSection";
import styles from "../styles/Home.module.css";
import ProjectsSlider from "../components/ProjectsSlider";

export default function Home() {
    const projParentRef = useRef(null);

	return (
		<div>
			<Head>
				<title>Daniel | About Me</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<StyledMain type="dark">
				<StyledSection sectionType="about">
					<div className="about-me-ctn">
						<a id="about" data-hs-anchor />

						<h1 className="section-title">&lt;about&gt;</h1>

						<div>
							<div>
								<h1>Daniel Chettiar</h1>
								<h2>Full Stack Developer</h2>
							</div>
							<div>
								<p>
									I care about building applications that look
									clean, and love working on the server side
									of things.
								</p>
								<p>
									When caught unsuspectingly, I&apos;m most
									probably trying to learn something new, or
									working on a project.
								</p>
							</div>
						</div>

						<div>
							<Image
								src={myImage}
								alt="My Picture"
								layout="responsive"
							/>
						</div>
					</div>
				</StyledSection>

				<StyledSection sectionType="projects">
					<div className="projects-ctn" ref={projParentRef}>
						<a id="projects" data-hs-anchor />

						<h1 className="section-title section-title--proj">
							&lt;projects&gt;
						</h1>

						<ProjectsSlider parentRef={ projParentRef }/>
					</div>
				</StyledSection>
			</StyledMain>
		</div>
	);
}

{
	/*<a id="about">
    asdhfkjashdjkfhkajsdhfjkahsjdkfas safshdfkjahsdf asdfasdfhaskdjf
</a>
<main className={styles.main}>
    <h1 className={styles.title}>
        Welcome to <a href="https://nextjs.org">Next.js!</a>
    </h1>

    <p className={styles.description}>
        Get started by editing{' '}
        <code className={styles.code}>pages/index.js</code>
    </p>

    <div className={styles.grid}>
        <a href="https://nextjs.org/docs" className={styles.card}>
        <h2>Documentation &rarr;</h2>
        <p>Find in-depth information about Next.js features and API.</p>
        </a>

        <a href="https://nextjs.org/learn" className={styles.card}>
        <h2>Learn &rarr;</h2>
        <p>Learn about Next.js in an interactive course with quizzes!</p>
        </a>

        <a
        href="https://github.com/vercel/next.js/tree/canary/examples"
        className={styles.card}
        >
        <h2>Examples &rarr;</h2>
        <p>Discover and deploy boilerplate example Next.js projects.</p>
        </a>

        <a
        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        className={styles.card}
        >
        <h2>Deploy &rarr;</h2>
        <p>
            Instantly deploy your Next.js site to a public URL with Vercel.
        </p>
        </a>
    </div>
</main> 
<footer className={styles.footer}>
    <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
    >
        Powered by{" "}
        <span className={styles.logo}>
            <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
            />
        </span>
    </a>
</footer>
*/
}

{
	/* <div>
								<h1>Socio</h1>
								<h2>A social media platform</h2>
								<p className="inferences">
									I started the project to learn how to build
									an application from scratch that was
									relatively complex for my level of
									competence at the time, tested the knowledge
									I had, and posed challenges so that the
									project provided room to learn and grow.{" "}
									<br />
									And by the end I developed a good
									understanding of React, Redux, NodeJS, got
									my first brush with AWS, namely S3 and RDS,
									and grasped the fact as to why project
									management is said to be one of the most
									important things to keep in mind as a
									developer.
								</p>
							</div>

							<div>
								<ul>
                                    <p>This is an application where...</p>
									<li>
										<p>
											You can create
											posts by text, photos, or both. Like
											them, comment on them.
										</p>
									</li>
									<li>
										<p>
											Get notified of all activities that
											you have subscribed to, for ex. a
											new post by a friend, a new like or
											comment on your post, etc, by push
											notifications, to your desktop, and
											mobile devices.
										</p>
									</li>
									<li>
										<p>
											Features a live chat messaging
											service.
										</p>
									</li>
									<li>
										<p>
											Uses service workers to process
											messages pushed by the server. Used
											to deliver push notifications,
											in-app notifications and power the
											live chat.
										</p>
									</li>
									<li>
										<p>Features custom theming</p>
									</li>
								</ul>
							</div>

							<div></div> */
}
